---

- name: Read inventory file
  ansible.builtin.include_vars:
    file: "{{ ansible_inventory_sources[0] }}"

- name: Render Prometheus configuration template
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_file }}"
    owner: root
    group: root
    mode: 0644
  vars:
    hosts: "{{ groups['builder'] | union(groups['controller']) | union(groups['prod']) }}"
  notify:
    - Restart Prometheus service
