prod:
  hosts:
    raspberry_1:
      ansible_host: 192.168.10.40
      ansible_ssh_user: raspi1
    raspberry_2:
      ansible_host: 192.168.10.41
      ansible_ssh_user: raspi2
    raspberry_3:
      ansible_host: 192.168.10.39
      ansible_ssh_user: raspi3

k3s_prod:
  children:
    server:
      hosts:
        raspberry_1:
          ansible_host: 192.168.10.40
          ansible_ssh_user: raspi1
        raspberry_2:
          ansible_host: 192.168.10.41
          ansible_ssh_user: raspi2
        raspberry_3:
          ansible_host: 192.168.10.39
          ansible_ssh_user: raspi3
    agents:
      hosts:
        raspberry_4:
          ansible_host: 192.168.10.42
          ansible_ssh_user: raspi4

all:
  vars:
    ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
