controller:
  hosts:
    pinas:
      ansible_host: 192.168.10.20
      ansible_ssh_user: pi

builder:
  hosts:
    raspberry_5:
      ansible_host: 192.168.10.120
      ansible_ssh_user: raspi5

monitoring:
  hosts:
    monitoring:
      ansible_host: 192.168.10.42
      ansible_ssh_user: monitoring

prod:
  hosts:
    raspberry_1:
      ansible_host: 192.168.10.6
      ansible_ssh_user: ubuntu
    raspberry_2:
      ansible_host: 192.168.10.4
      ansible_ssh_user: ubuntu
    raspberry_3:
      ansible_host: 192.168.10.11
      ansible_ssh_user: ubuntu

k3s_prod:
  children:
    server:
      hosts:
        raspberry_1:
          ansible_host: 192.168.10.6
          ansible_ssh_user: ubuntu
        raspberry_2:
          ansible_host: 192.168.10.4
          ansible_ssh_user: ubuntu
        raspberry_3:
          ansible_host: 192.168.10.11
          ansible_ssh_user: ubuntu
    agents:
      hosts:
        raspberry_4:
          ansible_host: 192.168.10.42
          ansible_ssh_user: raspi4

all:
  vars:
    ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"   # Path to the private key on the control node. Default is ~/.ssh/id_rsa
