---
auth_enabled: false

server:
  http_listen_port: 3100
  log_level: info

memberlist:
  join_members: ["loki-read", "loki-write"]
  bind_port: 7946

common:
  path_prefix: /loki
  compactor_address: http://loki-backend:3100
  replication_factor: 1
  storage:
    s3:
      bucketnames: loki-data
      endpoint: minio:9000
      access_key_id: loki
      secret_access_key: supersecret
      insecure: true
      s3forcepathstyle: true
  ring:
    kvstore:
      store: memberlist

schema_config:
  configs:
  - from: 2024-01-10
    store: tsdb
    object_store: s3
    schema: v12
    index:
      prefix: index_
      period: 24h

ruler:
  storage:
    s3:
      bucketnames: loki-ruler

table_manager:
  retention_deletes_enabled: true
  retention_period: 336h

compactor:
  working_directory: /tmp/compactor
